
@host = http://localhost:3000

###
// Inscription !!
POST {{host}}/auth/signup http/1.1
content-type: application/json

{
    "email": "bonjour@mail.com",
    "name": "greggo",
    "password": "azerty"
}


###
// Se logger !!

# @name login
POST {{host}}/auth/login  HTTP/1.1
content-type: application/json

{

    "email": "bonjour@mail.com",
    "name": "greggo",
    "password": "azerty"
}

###
// Ajouter un virus (se logger avant ^) !!
@authToken = {{login.response.body.token}}
@userId = {{login.response.body.userId}}
POST {{host}}/virus/upload HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----grego

------grego
Content-Disposition: form-data; name="userId"

{{userId}}
------grego
Content-Disposition: form-data; name="image"; filename = "imange.png"
Content-Type: image/png

< ./image/image.png
------grego--
